services:
  backend:
    container_name: url_shortener_backend
    build: ./backend
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    ports:
      - 8080:8080
    restart: unless-stopped
  frontend:
    container_name: url_shortener_frontend
    build: ./frontend
    ports:
      - 4321:80
    restart: unless-stopped
